version: 2.1

orbs:
  node: circleci/node@1.1.6
  coveralls: coveralls/coveralls@1.0.4
  win: circleci/windows@2.2.0

jobs:
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-windows-{{ checksum "package-lock.json" }}
      - npm i
      - save_cache:
          key: dependency-cache-windows-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - npm t
      - run:
          command: bash scripts/package.sh
          shell: bash.exe

workflows:
    master:
      jobs:
        - build-windows