version: 2.1

orbs:
  node: circleci/node@2.1.0
  coveralls: coveralls/coveralls@1.0.4
  win: circleci/windows@2.2.0

jobs:
  build-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          command: node/install-packages
          shell: bash.exe
      - run: npm t
      - run:
          command: bash scripts/package.sh
          shell: bash.exe

  build-macos:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - node/install-packages
      - run: npm t
      - run: scripts/package.sh

  build-linux:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
      - run: npm run test:all:coverage
      - run: npm run e2e:uws
      # Package time
      - run: apt-get install ruby ruby-dev rubygems build-essential
      - run: gem install --no-document fpm || echo "fpm install failed"
      - run: scripts/package.sh

workflows:
    master:
      jobs:
        - build-linux
        - build-windows
        - build-macos